version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8000:8000'

volumes:
  postgres_data:
