"""populate events

Revision ID: 0fc1dd0e2a6b
Revises: 3128749f7707
Create Date: 2025-08-29 21:58:14.992471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fc1dd0e2a6b'
down_revision: Union[str, Sequence[str], None] = '3128749f7707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insert_sql = """
        INSERT INTO events (event_name, event_date) 
        VALUES ('Event #1', '2026-01-01'), ('Event #2', '2026-01-02');
    """
    op.execute(insert_sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    delete_sql = """
        DELETE FROM events WHERE event_name in ('Event #1', ''Event #2')
    """
    op.execute(delete_sql)
    # ### end Alembic commands ###
