"""update status column in tickets

Revision ID: 485fdec62063
Revises: 0fc1dd0e2a6b
Create Date: 2025-08-29 22:14:01.247076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '485fdec62063'
down_revision: Union[str, Sequence[str], None] = '0fc1dd0e2a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'BOOKED', name='ticketstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('AVAILABLE', 'RESERVED', 'BOOKED', name='ticketstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
