"""populate tickets

Revision ID: 6ad47810a26a
Revises: 485fdec62063
Create Date: 2025-08-29 22:14:38.336940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ad47810a26a'
down_revision: Union[str, Sequence[str], None] = '485fdec62063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insert_sql = f"""
        INSERT INTO tickets (id, event_id, status) VALUES 
        ('bf2af413-dd2f-4dd2-a0e1-13def2abe020', '1', 'available'),
        ('94c60c55-0e59-41b3-9f56-55a67ddef42f', '1', 'available'),
        ('410c82b1-d33a-4eec-b93f-9b42f66f1000', '1', 'available'),
        ('b34b2e03-edba-46bb-884d-d64a30e3886a', '1', 'available'),
        ('c6f0078a-224a-449c-aeb8-0a81fbba1e8a', '1', 'available'),
        ('cfae7a8f-4d1f-4ac0-aab7-fb46b3f9f420', '2', 'available'),
        ('664047f8-3253-41e4-98d6-9416cd3af9d4', '2', 'available'),
        ('bf03a62f-338c-4b13-a291-2d52152fcfa0', '2', 'available'),
        ('fef88ffa-a9e2-425a-86d0-c8d0b4c5555d', '2', 'available'),
        ('91691830-bd26-4ebf-9f8c-b8e15bdbf136', '2', 'available')
    """
    op.execute(insert_sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    delete_sql = """
        DELETE FROM tickets WHERE id IN (
            'bf2af413-dd2f-4dd2-a0e1-13def2abe020',
            '94c60c55-0e59-41b3-9f56-55a67ddef42f',
            '410c82b1-d33a-4eec-b93f-9b42f66f1000',
            'b34b2e03-edba-46bb-884d-d64a30e3886a',
            'c6f0078a-224a-449c-aeb8-0a81fbba1e8a',
            'cfae7a8f-4d1f-4ac0-aab7-fb46b3f9f420',
            '664047f8-3253-41e4-98d6-9416cd3af9d4',
            'bf03a62f-338c-4b13-a291-2d52152fcfa0',
            'fef88ffa-a9e2-425a-86d0-c8d0b4c5555d',
            '91691830-bd26-4ebf-9f8c-b8e15bdbf136'
        )
    """
    op.execute(delete_sql)
    # ### end Alembic commands ###

